### PR TITLE
Add missing SPDX headers

### PR DESCRIPTION
**Pull request by johnsonjh**

### CODE REVIEW

**Review by aremmell — APPROVED** [review]

**Comment by aremmell** [comment]
@johnsonjh either I'm getting on the slow bus today, or something is wrong with our _sir_strncpy impl that uses strlcpy on macOS. I am getting the cpy >= destsz assert every time. according to the man page, it should only return >= destsz if truncation occurred. can you take a look while I debug this plugin stuff?

**Review by aremmell — APPROVED** [review]

**Comment by aremmell** [comment]
@johnsonjh 2ez

```
_sir_plugin_load (sirplugins.c:72): loaded plugin file (path: './build/lib/dummy_plugin.so', addr: 0x7ff90929fa80, id: 5fc3a195); probing...
_sir_plugin_getexport (sirplugins.c:161): resolved plugin export (name: 'sir_plugin_query', addr: 0x1000afe50)
_sir_plugin_getexport (sirplugins.c:161): resolved plugin export (name: 'sir_plugin_init', addr: 0x1000afea0)
_sir_plugin_getexport (sirplugins.c:161): resolved plugin export (name: 'sir_plugin_write', addr: 0x1000afec0)
_sir_plugin_getexport (sirplugins.c:161): resolved plugin export (name: 'sir_plugin_cleanup', addr: 0x1000afee0)
dummy_plugin(sir_plugin_query)
_sir_plugin_probe (sirplugins.c:129): successfully loaded plugin (path: './build/lib/dummy_plugin.so', id: 5fc3a195); properties:
{
	maj_ver = 1
	min_ver = 0
	bld_ver = 0
	levels = 00c0
	opts = 00004400
	author = 'libsir contributors'
	desc = 'Does nothing interesting. Logs messages to stdout.'
	caps = 0000000000000000
}
_sir_plugin_cache_add (sirplugins.c:244): added plugin (path: ./build/lib/dummy_plugin.so, id: 5fc3a195) to cache; count = 1
```

**Comment by johnsonjh** [comment]
On Mac, we're using the system provided strl* stuff ... it'll be a bit before I can get into it, but, if we want to we can switch to the internal one we added.

**Comment by aremmell** [comment]
N/M, the assert statement was backwards.

**Pull request merged**
