### PR TITLE
Add support for Solaris, illumos, DragonFly BSD, NetBSD, IBM AIX, Haiku, and Linux/musl

### PR DESCRIPTION
**Pull request by johnsonjh**
## Tests passing, fully working                          

* AIX (7.2 TL5 SP6 and 7.3 TL0 SP1)                            
  * IBM Open XL C/C++ V17.1.1 FP4              
  * GCC 11.3.0                                 
  * GCC 10.3.0                                 
  * GCC 8.3.0                                  
[]()
[]()
* NetBSD (9.3_STABLE)
  * Clang 15.0.6
  * GCC 13.1.0
  * GCC 12.2.0
  * GCC 7.5.0
[]()
[]()
* DragonFly BSD (6.4.0 and 6.5-DEV)
  * GCC 13.0.0
  * GCC 12.2.0
  * GCC 8.3.0
[]()
[]()
* Linux/musl                                   
  * GCC                                        
  * Clang                                      
  * NVIDIA HPC SDK C Compiler                  
[]()
[]()
* Oracle Solaris (11.4)
  * GCC 11.2.0
  * Clang 11.0.0
[]()
[]()
* illumos (OpenIndiana Hipster)
  * GCC 11.3.0
  * GCC 10.4.0
  * GCC 7.5.0
[]()
[]()
* Haiku
  * GCC 11.2.0
  * Clang 12.0.1
                                               
## Not yet working

* IBM XL C/C++ V16.1.0 FP14 on AIX - no `stdatomic.h`
* Clang on DragonFly BSD - no `stdatomic.h`
* Oracle Developer Studio C 12.6 on Solaris - unable to resolve thread local attribute
* MinGW/MSVCRT - no `_set_thread_local_invalid_parameter_handler`

## Future plans

* OpenBSD
* GNU/Hurd
* IBM XL C/C++ V16.1 for AIX and Linux
* IBM Open XL C/C++ V17.1 for Linux
* Oracle Studio Compiler for Linux and Solaris

### CODE REVIEW

**Comment by johnsonjh** [comment]
@aremmell   heyooo  o/

Please look this one over, when you get a chance.  You might want to do a bit more cleanup, but tests are all passing as noted.

**Comment by johnsonjh** [comment]
Also, I tested and I made sure I didn't break anything on macOS or FreeBSD.

**Comment by johnsonjh** [comment]
@aremmell 

I'll rebase this, but probably should do so after #45 if you approve.

**Comment by johnsonjh** [comment]
@aremmell 

I'm not very familiar with Travis CI - we use GitLab CI for our CI/CD purposes...

Screenshot from 2023-06-26 03-39-55

Is there any way to setup a self-hosted runner, and I'd add jobs for Solaris, OpenIndiana, AIX, NetBSD, OpenBSD, Haiku, etc?  I guess, worst case scenario, once I add sir to DPS8M, it'll start getting tested that way via our CI.

**Comment by johnsonjh** [comment]
Added NetBSD support; tested and working.

**Comment by johnsonjh** [comment]
Added Solaris and illumos support

**Comment by johnsonjh** [comment]
@aremmell I had to not use %zu - it was causing problems on AIX and others, either that or I would have to explicitly cast everything, but that's only for the test file, of course.

**Comment by johnsonjh** [comment]
Sorry, didn't get a chance for the CI.  It'll have to wait for the weekend.

**Comment by johnsonjh** [comment]
Last CI failure is a problem with the CI configuration and not related to the last commit.

**Comment by aremmell** [comment]
> @aremmell
> 
> I'm not very familiar with Travis CI - we use GitLab CI for our CI/CD purposes...
> 
> Screenshot from 2023-06-26 03-39-55
> 
> Is there any way to setup a self-hosted runner, and I'd add jobs for Solaris, OpenIndiana, AIX, NetBSD, OpenBSD, Haiku, etc? I guess, worst case scenario, once I add sir to DPS8M, it'll start getting tested that way via our CI.

I have a self-hosted GitLab instance on CentOS. Does that help?

**Comment by aremmell** [comment]
Can you resolve the conflicts, then I'll merge? Don't want to break anything that you've done.

**Comment by johnsonjh** [comment]
> Can you resolve the conflicts, then I'll merge? Don't want to break anything that you've done.

Sure thing - give me the day or so!

**Comment by johnsonjh** [comment]
> I have a self-hosted GitLab instance on CentOS. Does that help?

I'll look at making a `.gitlab-ci.yml` file and I can register some self-hosted runners to that project, either on your end or GitLab HQ, and we can setup GitLab to mirror GitHub.  I'll do a quick look at how runners work on GitHub first though, just to see if that's easier.

**Comment by johnsonjh** [comment]
@aremmell Do you know if there is an alternative to `_set_thread_local_invalid_parameter_handler` or if you can do without it?

That one function means needing UCRT vs. MSVCRT, and most MinGW toolchains and builds target MSVCRT at this time.

**Comment by aremmell** [comment]
We can toss it. I was trying to find a good way to check a file descriptor on windows. That one works, BUT it will terminate the process if it's invalid (and you don't hook the invalid parameter callback).

Maybe a simple `fstat()` and checking errno after will suffice.

**Comment by johnsonjh** [comment]
See [Discussions](https://github.com/aremmell/libsir/discussions).

**Comment by johnsonjh** [comment]
I'll close this one and submit again iteratively.

**Pull request closed without merging**
