### PR TITLE
Modify README and regen docs (closes #100)

### LINKED ISSUE #100: Doxygen doesn't parse TOC
The TOC in README.md results in a TOC on the main page of the documentation that's just text.

### PR DESCRIPTION
**Pull request by johnsonjh**
Closes #100 

Please squash when merging

### CODE REVIEW

**Comment by johnsonjh** [comment]
Not yet ...

**Comment by aremmell** [comment]
I was just going to say that we should probably have the same version of Doxygen haha

**Review by aremmell — APPROVED** [review]

**Comment by johnsonjh** [comment]
Merging master real quick ...

**Comment by johnsonjh** [comment]
Done, ready to go

**Pull request merged**
