### PR TITLE
Fix a typo in the example program

### PR DESCRIPTION
**Pull request by johnsonjh**
* Fix a typo in the example program

### CODE REVIEW

**Review by aremmell — APPROVED** [review]
How did that work?

**Comment by johnsonjh** [comment]
> How did that work?

It worked through the magic of luck (and alignment).  It usually said 0.0 and I never gave it a thought.

And then my little MIPS system said: `[warn] MyFooServer(62211): Detected downgraded link speed on eth0: last transfer rate: 14457935919346138118520009341732972848540587023673880701215377903225352839497160800222978796693163142
383766879915895397872065942685538155642167076290323411809177960448.0 KiB/s` so I decided to look at it. 🤣

**Comment by johnsonjh** [comment]
>  ... so I decided to look at it. 🤣


this makes me think ... perhaps we can leverage the new format verification stuff in GCC.  Pretty sure we can...

**Comment by johnsonjh** [comment]
> >  ... so I decided to look at it. 🤣
> 
> 
> this makes me think ... perhaps we can leverage the new format verification stuff in GCC.  Pretty sure we can... 

Oh yea!  https://gcc.gnu.org/onlinedocs/gcc/Common-Function-Attributes.html#index-format-function-attribute

**Comment by aremmell** [comment]
It doesn't give me much confidence in `_FORTIFY_SOURCE`, that's for sure. This regressed at some point; I know for sure it worked a few weeks back (or else it would say 0.0 in the sample screenshot).

**Comment by aremmell** [comment]
> > > ... so I decided to look at it. 🤣
> > 
> > 
> > this makes me think ... perhaps we can leverage the new format verification stuff in GCC.  Pretty sure we can...
> 
> Oh yea! https://gcc.gnu.org/onlinedocs/gcc/Common-Function-Attributes.html#index-format-function-attribute

Sweet. We should create a new issue for this.

**Comment by johnsonjh** [comment]
> It doesn't give me much confidence in `_FORTIFY_SOURCE`, that's for sure. This regressed at some point; I know for sure it worked a few weeks back (or else it would say 0.0 in the sample screenshot).

Fortify is only good for checking bounds pretty much.  The level "3" of fortify is nicer, but not widely supported.  I did check with "3" and nothing bad happened ...

**Pull request merged**
