### PR TITLE
Flawfinder

### PR DESCRIPTION
**Pull request by aremmell**
Will you look this over, and make sure I didn't botch anything? The flawfinder stuff is pretty straightforward:

- use strnlen instead of strlen
- use strlcpy/strlcat when available instead of strncpy/strncat

I moved a few things around to better fit the format that was already in place (i.e. where platform-specific includes are placed, etc.), and broke some long lines.

### CODE REVIEW

**Comment by aremmell** [comment]
I would like to assume I can replace `__FreeBSD__` with `__BSD__` in the strl code, but I don't have any other BSDs to test with, so I'll leave that up to you...

**Comment by johnsonjh** [comment]
Sure, I'll test it in the morning, and I'll check on strl availability as well.

**Comment by johnsonjh** [comment]
> I would like to assume I can replace `__FreeBSD__` with `__BSD__` in the strl code, but I don't have any other BSDs to test with, so I'll leave that up to you...

I've see that NetBSD, OpenBSD, and DragonFly BSD all have strlcat and strlcpy.  I'll change the check for \_\_FreeBSD\_\_ to the more general \_\_BSD\_\_.

**Comment by johnsonjh** [comment]
I need to revert the change that includes sys/param.h later.  

That won't work because it breaks the checks for \_\_DragonFly_version and \_\_FreeBSD_version which are defined there, so it needs to happen very early.

**Review by johnsonjh — APPROVED** [review]
@aremmell With the two changes I pushed it should be good, pending your OK.

**Comment by aremmell** [comment]
Awesome, thanks for doing that.

**Pull request merged**
