### PR TITLE
Add support for SerenityOS

### PR DESCRIPTION
**Pull request by johnsonjh**
* Add support for SerenityOS

### CODE REVIEW

**Comment by johnsonjh** [comment]
Don't merge yet - so far, only tested building (via cross-compilation); running the test suite (under QEMU/KVM) will have to wait until tonight.

**Review by aremmell — APPROVED** [review]

**Comment by johnsonjh** [comment]
Screenshot from 2023-07-13 22-03-07

@aremmell good to go ...

**Review by aremmell — APPROVED** [review]

**Comment by johnsonjh** [comment]
@aremmell Probably the weirdest port? 🥇   You said you know the author?  He answered a few questions online today, and they're usually helpful there.  I had already ported DPS8M already before, so this keeps it working.

**Comment by johnsonjh** [comment]
Going out for a bit and then AIX I guess - nothing else to distract me from the last one I need :)

**Comment by aremmell** [comment]
I don't know him, I just heard he used to work on WebKit.

**Comment by aremmell** [comment]
> Going out for a bit and then AIX I guess - nothing else to distract me from the last one I need :)

Right on. I'm tinkering with Rust.

**Comment by johnsonjh** [comment]
SerenityOS is really strange.  They don't port anything that's in the base OS - everything is always a new and from-scatch implementation.  They have their own web browser and their own JavaScript engine - https://awesomekling.github.io/Ladybird-a-new-cross-platform-browser-project/ ...

**Comment by aremmell** [comment]
Yea, sounds like that guy went a tiny bit Ted Kaczynski

**Pull request merged**
